### ISSUE TITLE
Ensure Object Creation is Delegated

### ISSUE THREAD

**Issue by Michael-DST** [PrismLibrary/Prism.Wpf#3]
Another issue that I am finding.  Here are two (grouped) examples:

1) https://github.com/PrismLibrary/Prism.Wpf/blob/master/Source/Prism.Interactivity/PopupWindowAction.cs#L146

2) https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Events/PrismEvent.cs#L110
https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Events/PrismEvent.cs#L113
https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Events/PrismEvent.cs#L117

The first example is easier to spot.  Let's say my project is using a 3rd party control with its own dialog:
https://github.com/firstfloorsoftware/mui/blob/master/1.0/FirstFloor.ModernUI/Shared/Windows/Controls/ModernDialog.cs

How do I tie into this action?  Well, since the creation is not delegated to a protected/virtual, I have to essentially override that method and copy/paste adjust.  Hardly optimal.

The 2nd is more of a design issue in general, and probably not so obvious (and I am probably using it wrong).  I am overriding this object with my own Xamarin.Forms event adapter:
https://github.com/DragonSpark/Framework/blob/77c9fd604968b5140c744c37eedb1e4c6010d38b/DragonSpark.Client/FormsEvent.cs

Xamarin.Forms uses a notion of a subscriber object.  The Prism signature doesn't offer this, so I added my own (line 32).  But now how to store it?  If these instantiation methods were delegated, I would be able to create my own subscription types that override the 3 that are already defined and tie into Prism's pub-sub perfectly.  Instead, I have to use a less optimal one (for now).

Again, I probably am not using this the best way, so it's not as clear/obvious as the first issue.

Just a thought. :)

**Comment by brianlagunas** [comment]
For now, you would have to create a derived implementation of PopupWindowAction and override GetWindow.  Though, it should be relatively easy to modify that to make it more extensible.

As for your second question, I'm not really sure I get what you are asking.  Are you wanting to pass the sender of the event along with the event?  What would be the need for that?  Event aggregation if a fire and forget eventing system.  Ideally you would only pass the bare minimum information, like an ID, that any subscribers may need to respond to the event.  If you really want to pass the sender of the event, just pass it as a parameter, but I would challenge your need to do so.

**Comment by Michael-DST** [comment]
Cool... yeah, I just wanted to bring it up for awareness sake.  If I can, I will submit a PR around it once I get into the code.

As for the 2nd issue... the need is to wrap around the Xamarin.Forms MessagingCenter.  It requires a subscriber object to subscribe/unsubscribe (even though in the end it is not even used).  It also uses a string for messaging, which is not as strong as using a strongly-typed event object.  So the idea is to make both Prism and MessagingCenter play along nicely.

Like I said, it's not as clear as the first example.  I just wanted to point that that in the case of creating objects, it's always nice to have that delegated to a factory/protected-virtual method for extensions to tie into.

**Comment by brianlagunas** [comment]
Is there a reason you want to rely on the XF Messaging system?  Prism manages all the publishers and subscribers for you.  You don't have to worry about unsubscribing.  Simply publish an event, on whatever thread you want, and any subscribers will receive the message with any parameters you passed.

**Comment by Michael-DST** [comment]
I agree, and that's what I use Prism for (and feel it's the superior approach/implementation here), but I also want to have strongly-typed messages coming in *from* XF... there are events that get broadcasted from the internals, as well.  That's what I am also accounting for.  Yeah, I could use a string, but then I would have inconsistent approaches.  Not to mention having to deal with two different pubsub systems.  Using this approach, I have just one and they are talking to each other nicely.

**Comment by brianlagunas** [comment]
I also noticed you passing Application and Page objects through your event as parameters.  Of course, you would to avoid these types of events in any ViewModels.

**Comment by Michael-DST** [comment]
Ah you mean from the perspective of separation of concerns?  Or something else?  The Page is a Xamarin.Forms.Page, not a UI element, if that is what you mean. I am most definitely open to feedback.  It's not a one way street here. :)

**Comment by powerdude** [comment]
it would probably be best to consider Xamarin.Forms.Page as a UI element even though technically it isn't since it is tied to the UI "system"

**Comment by Michael-DST** [comment]
Yes I have yet to wrap my head around how exactly to cleanly map Element (Page) to UIElement/FrameworkElements.  Pages are literally models of views.  But, I see what you are saying.  I am working with what I got, and that is basically porting the Windows Phone 8 rendering system to WPF.  It's very surprising, but there aren't any viewmodels in the rendering system, and there is a *lot* of view-centric code that should be handled in Xaml.  I am guessing this is why it's all internal ATM (among other reasons). :P

**Comment by powerdude** [comment]
If it helps, i think of pages/elements as meta data for the platform specific pages/views.  The translation of the meta data to the platform specific stuff is the job of the renderer.  Most things are internal because of fear of exposing too much too soon when all functionality is fully-baked or tested yet.  At least, that's what i've gleaned from the past few months with the product.

**Comment by Michael-DST** [comment]
Yeah, it's metadata, but my feeling is that it is actually more than that... they actually represent actual view objects (actually, LOL).  You could make DataTemplates out of them if you wanted to.  In fact, that's how I am going to be approaching it and exploring in the next few weeks.  I am surprised that is not how they are rendered in the Phone.  There must be a limitation I am not aware of.  But in any case, it is an awesome (probably the best!) way of learning about the innerworkings of XF and getting familiar w/ how it works.  I am only two-ish weeks into it myself, so I am definitely appreciative of any feedback/guidance/thoughts you have on it. :)

**Comment by brianlagunas** [comment]
I added a virtual CreateWindow method to PopupWindowAction in the Prism 6 repo.  This should make it a little easier to provide your own Window without having to know anything about the internals.

**Comment by Michael-DST** [comment]
Man you are ON IT!  Thank you, Brian. :)
